config/routes.rb
Rails.application.routes.draw do

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :requests , only: [:index, :destroy]

  get '/req_info/all_req_info', to: 'req_info#index', as: 'req_infos'
  get '/:path_url/requests', to: 'req_info#req_list_by_url', as: 'req_list'

  match '/:path_url/*scheme', to: 'requests#check_req', via: :all, as: 'check_req'
  match '/:path_url', to: 'requests#check_req', via: :all, as: 'check_req_without_shem'

  root 'requests#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/req_info.rb
class ReqInfo < ApplicationRecord
  belongs_to :request

  after_create :req_info_send

  def req_info_send
    ActionCable.server.broadcast "req_channel",
                                 req_id: self.request.id,
                                 path_url: self.request.path_url

    ActionCable.server.broadcast "req_info_channel",
                                 req_id: self.request.id,
                                 path_url: self.request.path_url,
                                 req_inf_id: self.id,
                                 remote_ip: self.remote_ip,
                                 req_method: self.req_method,
                                 scheme: self.scheme,
                                 query_string: self.query_string,
                                 query_params: self.query_params,
                                 cookies: self.cookies,
                                 headers: self.headers
  end
end

app/models/request.rb
class Request < ApplicationRecord
  has_many :req_infos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/req_info_controller.rb
class ReqInfoController < ApplicationController
  def index
    @table_id = 'all'
    @req_infos = ReqInfo.all
  end

  def req_list_by_url

    @request = Request.find_by path_url: params['path_url']

    if @request == nil
      # @req_infos = []
      # @table_id = 'nil'

      render 'req_info/request_not_found'
    else
      @req_infos = @request.req_infos
      @table_id = @request.id

      render 'req_info/index'
    end

  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:destroy]

  def check_req

    @req = request

    @request = Request.find_or_create_by(path_url: params['path_url'])

    headers = request.headers.env.select{|k, _| k =~ /^HTTP|^REQUEST|^SERVER|^QUERY|PATH/}

    @info = @request.req_infos.create(
        remote_ip: @req.remote_ip,
        req_method: @req.request_method,
        scheme: params['scheme'],
        query_string: @req.query_string,
        query_params: params,
        cookies: @req.cookies,
        headers: headers.to_s
    )

    respond_to do |format|
      format.html { redirect_to requests_url}
      format.js
    end
  end

  def index
    @req = request
    @requests = Request.all
  end

  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.permit(:path_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/req_info_helper.rb
module ReqInfoHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <div>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to 'Requests-Trap', requests_path, class: 'navbar-brand' %>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Home', requests_path %></li>
          <li><%= link_to 'All info', req_infos_path %></li>
          <!--<li><a href="#">Page 2</a></li>-->
        </ul>
        <!--<form class="navbar-form navbar-left" action="/action_page.php">-->
          <!--<div class="form-group">-->
            <!--<input type="text" class="form-control" placeholder="Search">-->
          <!--</div>-->
          <!--<button type="submit" class="btn btn-default">Submit</button>-->
        <!--</form>-->
      </div>
    </nav>
  </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/req_info/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Info requests</h1>
<h1>Info</h1>

<div class="container">
  <div class="row">
    <table id="req_info" class="table" data-id="<%= @table_id %>">
      <thead>
      <tr>
        <th>path_url</th>
        <th>remote_ip</th>
        <th>req_method</th>
        <th>scheme</th>
        <th>query_string</th>
        <th>query_params</th>
        <th>cookies</th>
        <th>headers</th>
        <th colspan="3">action</th>
      </tr>
      </thead>

      <tbody>
      <% @req_infos.each do |request| %>
        <tr>
          <td><%= request.request.path_url %></td>
          <td><%= request.remote_ip %></td>
          <td><%= request.req_method %></td>
          <td><%= request.scheme %></td>
          <td><%= request.query_string %></td>
          <td><%= request.query_params %></td>
          <td><%= request.cookies %></td>
          <td><%= request.headers %></td>

        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/req_info/request_not_found.html.erb
<h1>request_not_found</h1>
<li><%= link_to 'Back to all request info', req_infos_path %></li>

app/views/requests/_form.html.erb
<%= form_with(model: request, local: true) do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :path_url %>
    <%= form.text_field :path_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/requests/_formImitation.html.erb
<div class="row">
  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">

    <p>action_url: '<span id="show_url">twitter/some_scheme</span>'</p>
    <%= form_with(url: 'twitter/some_scheme', method: "PUT", remote: true, format: :json, :id => 'form_change') do |form| %>

      <div class="form-group">
        <%= form.label :url %>
        <%= form.text_field :url, :id => 'url', :value => 'twitter/some_scheme', required: true, :onkeyup => "change_action(this)" %>
        <br>

        <%= select_tag(
                :method,
                options_for_select([['GET', 'GET'], ['POST', 'POST'], ['PUT', 'PUT'], ['PATCH', 'PATCH'], ['DELETE','DELETE']], 'PUT'),
                :id => "method_option",
                :onchange => "change_method(this);")
        %>

      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<div id="alert_s" class="alert alert-success" hidden>
  <strong>Success!</strong> Request info was saved.
</div>

<h1>Index requests trap</h1>
<div class="container">
  <%= render 'formImitation', request: @request %>
</div>

<h1>Requests</h1>
<table id="req_list" class="table">
  <thead>
    <tr>
      <th>Url path</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= link_to "#{request.path_url}", "#{request.path_url}"+'/requests', id: "req_#{request.id}" %></td>
        <td>
          <%= link_to 'Show request statistic', "#{request.path_url}"+'/requests' %>
          ||
          <%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>